### ISSUE TITLE
Add `woodstox`, `java-classmate` under FasterXML?

### ISSUE THREAD

**Issue by cowtowncoder** [jodastephen/jpms-module-names#22]
I think that Woodstox 5.x, which does add automatic module name:

https://github.com/FasterXML/woodstox

is missing from under FasterXML section.

Similarly, if it belongs there, ClassMate:

https://github.com/FasterXML/java-classmate

(type introspection library)

has automatic module name included since version 1.3.4.

I can help dig up further libraries I maintain if that helps -- this seems like a valuable project so would be happy to help if there's something I can do.

**Comment by sormuras** [comment]
Are the two libraries published on Maven Central? Under which group?

> I can help dig up further libraries I maintain if that helps -- this seems like a valuable project so would be happy to help if there's something I can do.

Sure. PR's are welcome. Look at the logical table configuration files here: https://github.com/jodastephen/jpms-module-names/tree/master/generator/table

**Comment by cowtowncoder** [comment]
Yes, both are published to Maven Central. Artifact ids:

```xml
    <groupId>com.fasterxml.woodstox</groupId>
    <artifactId>woodstox-core</artifactId>
    <version>5.1.0</version>
```

```xml
     <groupId>com.fasterxml</groupId>
    <artifactId>classmate</artifactId>
    <version>1.4.0</version>
```

I'll hope to find time to look into configs and contribute. I just recently heard about this project.

**Comment by sormuras** [comment]
`com.ctc.wstx=com.fasterxml.woodstox:woodstox-core` is the diverging module name intended?

**Comment by sormuras** [comment]
Addressed via https://github.com/jodastephen/jpms-module-names/commit/f6ba461d728b0e2630fff64f06bdfd2a3204da6b

**Comment by cowtowncoder** [comment]
@sormuras Good question. It was chosen to align with Maven coordinates. Java package name is due to historical reasons, and would be changed if it wasn't for the fact that factory names are so widely used via properties / manifest files.
