### ISSUE TITLE
Add Flyway

### ISSUE THREAD

**Issue by axelfontaine** [jodastephen/jpms-module-names#23]
Automatic Module Name: org.flywaydb.core
Maven coordinates:  org.flywaydb:flyway-core:5.1.1
Homepage: https://flywaydb.org

**Comment by sormuras** [comment]
Strange **_name_** in http://central.maven.org/maven2/org/flywaydb/flyway-core/5.1.1/flyway-core-5.1.1.pom 🙂 

```xml
...
<artifactId>flyway-core</artifactId>
<packaging>jar</packaging>
<name>${project.artifactId}</name>
...
```

**Comment by sormuras** [comment]
Added via https://github.com/jodastephen/jpms-module-names/commit/9fefb86c4f74ae965534028c750e12849925cead

**Comment by axelfontaine** [comment]
Needless to say `${project.artifactId}` of course gets replaced by `flyway-core` during a Maven build.

You may therefore probably want to update your commit to prereplace this as well as the replacement value makes much more sense in this context.

**Comment by sormuras** [comment]
> Needless to say ${project.artifactId} of course gets replaced by flyway-core during a Maven build.

True.

But a) this project does not trigger Maven builds and b) a `name` can tell us humans a story that extends the meaning of the `artifactId`: https://maven.apache.org/pom.html#More_Project_Information ... so I extend "strange" with "limited".

**Comment by sormuras** [comment]
>You may therefore probably want to update your commit to prereplace this as well as the replacement value makes much more sense in this context.

Done via https://github.com/jodastephen/jpms-module-names/commit/9fce7c94a3acd6df2ef455c283c7674f4725be35
