### ISSUE TITLE
Update description that mentions Java 9

### ISSUE THREAD

**Issue by vietj** [jodastephen/jpms-module-names#27]
The actual repository mentions Java 9 which is confusing, since Java 9 is deprecated. I believe this part should only mentions JPMS and no specific Java version.

<img width="281" alt="screen shot 2019-01-21 at 08 51 24" src="https://user-images.githubusercontent.com/225674/51459747-db4c0d00-1d59-11e9-8298-161d44df170b.png">

**Comment by jodastephen** [comment]
Fixed thanks
