### ISSUE TITLE
Unexpected naming threeten-jaxb

### ISSUE THREAD

**Issue by mkroening** [jodastephen/jpms-module-names#28]
I just found the artifact `io.github.threeten-jaxb:threeten-jaxb-core` with the module name `io.github.threetenjaxb.core` to be listed under unexpected naming.

I suspect, that is because of the hyphens or because of the redundant artifact coordinates, but what exactly is the issue?

**Comment by sormuras** [comment]
Hi @mwkroening - thanks for raising this issue.

This is directly related to #26. For the time being, I enforce that the module name starts exactly with same characters as its Maven Group ID. This way I can be sure to have 1:1 mapping from a module name to a Maven artifact.

After adding the line `io.github.threeten-jaxb=io.github.threetenjaxb` into `maven-group-alias.properties` the module name should no longer be marked as unexpected. Next time the scanner sees a new version of `io.github.threeten-jaxb:threeten-jaxb-core` being published to Maven Central, it will be included in the mapping "database".

**Comment by mkroening** [comment]
Thanks a lot for clarification!

Shall I provide a PR?

**Comment by sormuras** [comment]
Done. ;-)
