### ISSUE TITLE
Netty module names

### ISSUE THREAD

**Issue by vietj** [jodastephen/jpms-module-names#5]
Netty has provided in its latest release 4.1.18.Final automatic module names for Java 9 : https://github.com/netty/netty/commit/e8540c2b7a1243618002c857be5ba463984e1b76

**Comment by jodastephen** [comment]
PR welcome

**Comment by sormuras** [comment]
Done via https://github.com/jodastephen/jpms-module-names/commit/6e757c5fad813255453bee0b63dfb77489b4fc0b - see generated modules table: https://github.com/jodastephen/jpms-module-names/blob/master/generated/modules.md
